// This file was auto-generated by Fern from our API Definition.

import { Imdb } from "./api/resources/imdb/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { mergeHeaders } from "./core/headers.js";
import * as core from "./core/index.js";

export declare namespace FernDemoApiClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class FernDemoApiClient {
    protected readonly _options: FernDemoApiClient.Options;
    protected _imdb: Imdb | undefined;

    constructor(_options: FernDemoApiClient.Options) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "@fern-demo/imdb-typescript-sdk",
                    "X-Fern-SDK-Version": "0.0.29",
                    "User-Agent": "@fern-demo/imdb-typescript-sdk/0.0.29",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get imdb(): Imdb {
        return (this._imdb ??= new Imdb(this._options));
    }
}
